name: ERP API
on:
  pull_request:
    branches:
      - master

defaults:
  run:
    working-directory: api_erp

jobs:
  stages:
    - test

  # Variables
  variables:
    MYSQL_ROOT_PASSWORD: root
    MYSQL_USER: root
    MYSQL_PASSWORD: root
    MYSQL_DATABASE: erp_api
    DB_HOST: mysql

  test:
    stage: test
    services:
      - mysql:5.7
    image: edbizarro/gitlab-ci-pipeline-php:8.0-alpine
    script:
      - yarn install --pure-lockfile
      - composer install --prefer-dist --no-ansi --no-interaction --no-progress
      - cp .env.example .env
      - php artisan key:generate
      - php artisan migrate:refresh --seed
      - ./vendor/phpunit/phpunit/phpunit -v --coverage-text --colors=never --stderr
